openapi: 3.0.0
info:
  title: SalesOps Enterprise Mock API
  description: Simulated internal API for Ticketing, Email, and CRM.
  version: 1.0.0
servers:
  - url: http://localhost:7777
    description: Local Mock Server

paths:
  /tickets:
    post:
      summary: Create a Jira/ServiceNow ticket
      operationId: createTicket
      parameters:
        - in: header
          name: Idempotency-Key
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, priority, anomaly_id]
              properties:
                title:
                  type: string
                description:
                  type: string
                priority:
                  type: string
                  enum: [High, Medium, Low]
                anomaly_id:
                  type: string
                assignee:
                  type: string
      responses:
        "201":
          description: Ticket Created
        "409":
          description: Conflict (Idempotent replay)
        "422":
          description: Validation Error

  /emails/send:
    post:
      summary: Send an automated email
      parameters:
        - in: header
          name: Idempotency-Key
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [recipient, subject, body]
      responses:
        "202":
          description: Email Queued

  /admin/chaos:
    post:
      summary: Configure runtime failure simulation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                enabled: { type: boolean }
                failure_rate: { type: number }
                simulate_rate_limit: { type: boolean }

  /health:
    get:
      summary: Health check

  /ready:
    get:
      summary: Readiness check
