import streamlit as st
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[2]))

from dashboard.utils.style import apply_custom_css, sidebar_logo
from dashboard.utils.loaders import load_enriched

st.set_page_config(page_title="AI Explanations", page_icon="🧠", layout="wide")
apply_custom_css()
sidebar_logo()

st.title("🧠 AI Root Cause Analysis")
st.markdown(
    "Explanations generated by **Gemini 2.0** using Retrieval Augmented Generation (RAG)."
)

df = load_enriched()

if not df.empty:
    # 1. Overview Metrics
    high_conf = len(df[df["confidence"] == "High"])
    human_review = len(df[df["needs_human_review"] == True])

    c1, c2, c3 = st.columns(3)
    c1.metric("Explained Anomalies", len(df))
    c2.metric("High Confidence", high_conf)
    c3.metric("Needs Human Review", human_review, delta_color="inverse")  # Red if high

    st.markdown("---")

    # 2. Explanation Cards
    for idx, row in df.iterrows():
        with st.container():
            # Header
            c_head, c_conf = st.columns([3, 1])
            c_head.subheader(f"{row['entity_id']} ({row['metric']})")

            # Confidence Badge
            conf_color = "green" if row["confidence"] == "High" else "orange"
            c_conf.markdown(f"**Confidence:** :{conf_color}[{row['confidence']}]")

            # Main Content in "Card" style
            st.markdown(
                f"""
            <div class="card">
                <h4>📝 {row['explanation_short']}</h4>
                <p>{row['explanation_full']}</p>
                <hr>
                <strong>✅ Suggested Actions:</strong>
                <ul>
                    {''.join([f'<li>{a}</li>' for a in row.get('suggested_actions', [])])}
                </ul>
                <br>
                <small><em>Model: {row.get('model', 'Unknown')} | Latency: {row.get('latency', 0)}ms</em></small>
            </div>
            """,
                unsafe_allow_html=True,
            )

else:
    st.warning("No AI explanations available.")
